Repository jsonform/jsonform, pull requests merged in 2018-06, with the labels that each got.

#157 Add space character to placeholder string
  lib/jsonform.js
Labels: Bug

#146 Update underscore.js to 1.8.3
  deps/underscore.js
  lib/jsonform.js
Labels: Enhancement, Maintenance

#155 textarea misses fieldHtmlClass option
  lib/jsonform.js
Labels: Enhancement

#51 Add an icon select field.
  lib/jsonform.js
  playground/examples/fields-iconselect.json
  playground/playground.js
Labels: Enhancement
